### ISSUE TITLE
Seqeuence Wallet Support

### ISSUE THREAD

**Issue by AakifNadeem** [Ammar-Ishfaq/WalletConnect-V2-dapp#2]
Great Repo @Ammar-Ishfaq. how we connecting the sequence wallet with walletconnect v2?

**Comment by Ammar-Ishfaq** [comment]
Hi @AakifNadeem, you can use the QR Code in the bottom sheet's top right corner from there you can sign using sequence wallet however by default we don't have a similar option as we had for other wallets e.g: Trust wallet, MetaMask, etc.

**Comment by AakifNadeem** [comment]
Okay great
